# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Riffomonas Code Club
email: pschloss@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Code Club: An social effort learn to do reproducible data analysis
baseurl: "/code_club" # the subpath of your site, e.g. /blog
url: "https://www.riffomonas.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: patschloss
github_username:  riffomonas
repo: https://github.com/riffomonas/code_club


permalink: /:year-:month-:day-:title

layouts_dir: /resources/_layouts
includes_dir: /resources/_includes
sass:
  sass_dir: /resources/_sass
  style: compressed

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

# set timezone
timezone: America/New_York



future: false
